// Known providers. `re` is matched against payee + purpose text.
// `url` is only set where the account/cancel page is stable; everything else
// gets a search link and the letter generator instead of a guessed URL.
// Order matters: specific entries (Amazon Prime) must come before broad ones (Amazon).

export const CATEGORIES = [
  'video', 'music', 'audio', 'software', 'cloud', 'ai', 'news', 'fitness', 'gaming',
  'dating', 'learning', 'mobile', 'internet', 'tv', 'food', 'mobility', 'insurance',
  'energy', 'broadcast', 'housing', 'finance', 'charity', 'shopping', 'other',
];

// Categories that are typically optional and cancellable by the user.
export const SUBSCRIPTION_CATEGORIES = new Set([
  'video', 'music', 'audio', 'software', 'cloud', 'ai', 'news', 'fitness', 'gaming',
  'dating', 'learning', 'mobile', 'internet', 'tv', 'food', 'mobility', 'other',
]);

export const MERCHANTS = [
  // Video
  { name: 'Netflix', re: /netflix/i, cat: 'video', kind: 'video', url: 'https://www.netflix.com/cancelplan' },
  { name: 'Disney+', re: /disney\s*plus|disneyplus|disney\+/i, cat: 'video', kind: 'video' },
  { name: 'Amazon Prime', re: /amazon\s*prime|prime\s*video|amzn\s*prime|primevideo/i, cat: 'video', kind: 'video', url: 'https://www.amazon.de/mc' },
  { name: 'DAZN', re: /\bdazn\b/i, cat: 'video', kind: 'video' },
  { name: 'Sky / WOW', re: /\bsky\s*(deutschland|ticket)?\b|wow\s*tv|\bwowtv\b/i, cat: 'video', kind: 'video' },
  { name: 'RTL+', re: /rtl\s*\+|rtl\s*plus|rtlplus/i, cat: 'video', kind: 'video' },
  { name: 'Joyn', re: /\bjoyn\b/i, cat: 'video', kind: 'video' },
  { name: 'Paramount+', re: /paramount/i, cat: 'video', kind: 'video' },
  { name: 'Crunchyroll', re: /crunchyroll/i, cat: 'video', kind: 'video' },
  { name: 'YouTube TV', re: /youtube\s*tv|youtubetv/i, cat: 'tv', kind: 'livetv' },
  { name: 'Hulu', re: /\bhulu/i, cat: 'video', kind: 'video' },
  { name: 'Max', re: /\bhbo\b|hbo\s*max|\bmax\.com|hbomax/i, cat: 'video', kind: 'video' },
  { name: 'Peacock', re: /peacock/i, cat: 'video', kind: 'video' },
  { name: 'ESPN+', re: /espn/i, cat: 'video', kind: 'video' },
  { name: 'Starz', re: /\bstarz/i, cat: 'video', kind: 'video' },
  { name: 'Showtime', re: /showtime/i, cat: 'video', kind: 'video' },
  { name: 'AMC+', re: /amc\s*\+|amc\s*plus/i, cat: 'video', kind: 'video' },
  { name: 'NOW', re: /now\s*tv|nowtv/i, cat: 'video', kind: 'video' },
  { name: 'BritBox', re: /britbox/i, cat: 'video', kind: 'video' },
  { name: 'Sling TV', re: /\bsling/i, cat: 'tv', kind: 'livetv' },
  { name: 'Fubo', re: /\bfubo/i, cat: 'tv', kind: 'livetv' },
  { name: 'Philo', re: /\bphilo\b/i, cat: 'tv', kind: 'livetv' },
  { name: 'YouTube Premium', re: /youtube/i, cat: 'video', kind: 'video', url: 'https://www.youtube.com/paid_memberships' },
  { name: 'Apple TV+', re: /apple\s*tv/i, cat: 'video', kind: 'video' },
  { name: 'waipu.tv', re: /waipu/i, cat: 'tv', kind: 'livetv' },
  { name: 'Zattoo', re: /zattoo/i, cat: 'tv', kind: 'livetv' },
  { name: 'MagentaTV', re: /magenta\s*tv/i, cat: 'tv', kind: 'livetv' },
  { name: 'Twitch', re: /twitch/i, cat: 'video', kind: 'video' },
  // Music & audio
  { name: 'Spotify', re: /spotify/i, cat: 'music', kind: 'music', url: 'https://www.spotify.com/account/subscription/' },
  { name: 'Apple Music', re: /apple\s*music/i, cat: 'music', kind: 'music' },
  { name: 'Deezer', re: /deezer/i, cat: 'music', kind: 'music' },
  { name: 'Tidal', re: /\btidal\b/i, cat: 'music', kind: 'music' },
  { name: 'Amazon Music', re: /amazon\s*music|amzn\s*music/i, cat: 'music', kind: 'music' },
  { name: 'Pandora', re: /pandora/i, cat: 'music', kind: 'music' },
  { name: 'SiriusXM', re: /sirius\s*xm|siriusxm/i, cat: 'music' },
  { name: 'Audible', re: /audible/i, cat: 'audio', kind: 'audiobook' },
  { name: 'BookBeat', re: /bookbeat/i, cat: 'audio', kind: 'audiobook' },
  { name: 'Nextory', re: /nextory/i, cat: 'audio', kind: 'audiobook' },
  { name: 'Kindle Unlimited', re: /kindle\s*(unltd|unlimited)/i, cat: 'audio' },
  { name: 'Blinkist', re: /blinkist/i, cat: 'audio' },
  // Software & cloud
  { name: 'Xbox Game Pass', re: /xbox/i, cat: 'gaming' },
  { name: 'Microsoft 365', re: /microsoft|msbill|office\s*365/i, cat: 'software', url: 'https://account.microsoft.com/services' },
  { name: 'Adobe', re: /adobe/i, cat: 'software', url: 'https://account.adobe.com/plans' },
  { name: 'Dropbox', re: /dropbox/i, cat: 'cloud', kind: 'cloud', url: 'https://www.dropbox.com/account/plan' },
  { name: 'Google Fi', re: /google\s*fi\b/i, cat: 'mobile' },
  { name: 'Google One', re: /google\s*one|google\s*storage/i, cat: 'cloud', kind: 'cloud', url: 'https://myaccount.google.com/payments-and-subscriptions' },
  { name: 'Google Play', re: /google/i, cat: 'cloud', url: 'https://myaccount.google.com/payments-and-subscriptions' },
  { name: 'iCloud+', re: /icloud/i, cat: 'cloud', kind: 'cloud' },
  { name: 'Apple Services', re: /apple\.com|itunes|apple\s*services/i, cat: 'cloud' },
  { name: 'Canva', re: /canva/i, cat: 'software' },
  { name: 'Notion', re: /notion\.so|\bnotion\b/i, cat: 'software' },
  { name: '1Password', re: /1password|agilebits/i, cat: 'software', kind: 'password' },
  { name: 'NordVPN', re: /nordvpn|nordsec|nord\s*vpn/i, cat: 'software', kind: 'vpn' },
  { name: 'Surfshark', re: /surfshark/i, cat: 'software', kind: 'vpn' },
  { name: 'ExpressVPN', re: /expressvpn/i, cat: 'software', kind: 'vpn' },
  { name: 'CyberGhost', re: /cyberghost/i, cat: 'software', kind: 'vpn' },
  { name: 'Proton', re: /\bproton\b/i, cat: 'software' },
  { name: 'LastPass', re: /lastpass/i, cat: 'software', kind: 'password' },
  { name: 'Dashlane', re: /dashlane/i, cat: 'software', kind: 'password' },
  { name: 'Ring', re: /\bring\.com|ring\s*(protect|yearly|monthly)/i, cat: 'software' },
  { name: 'GitHub', re: /github/i, cat: 'software' },
  { name: 'Norton', re: /norton/i, cat: 'software' },
  { name: 'McAfee', re: /mcafee/i, cat: 'software' },
  { name: 'Kaspersky', re: /kaspersky/i, cat: 'software' },
  // AI
  { name: 'ChatGPT', re: /openai|chatgpt/i, cat: 'ai', kind: 'chatbot' },
  { name: 'Claude', re: /anthropic|claude\.ai/i, cat: 'ai', kind: 'chatbot' },
  { name: 'Midjourney', re: /midjourney/i, cat: 'ai' },
  { name: 'Perplexity', re: /perplexity/i, cat: 'ai', kind: 'chatbot' },
  // News
  { name: 'Der Spiegel', re: /spiegel/i, cat: 'news' },
  { name: 'Die Zeit', re: /zeit\s*online|zeitverlag|\bdie zeit\b/i, cat: 'news' },
  { name: 'FAZ', re: /\bfaz\b|frankfurter allgemeine/i, cat: 'news' },
  { name: 'Süddeutsche', re: /sueddeutsche|süddeutsche|\bsz\s*plus/i, cat: 'news' },
  { name: 'BILDplus', re: /bild\s*plus|bildplus|axel springer/i, cat: 'news' },
  { name: 'Handelsblatt', re: /handelsblatt/i, cat: 'news' },
  { name: 'The New York Times', re: /ny\s*times|nytimes|new york times/i, cat: 'news' },
  { name: 'The Wall Street Journal', re: /wall street journal|\bwsj\b|dow jones/i, cat: 'news' },
  { name: 'The Washington Post', re: /washington\s*post|washpost/i, cat: 'news' },
  { name: 'The Times', re: /times\s*digital|thetimes|times newspapers/i, cat: 'news' },
  { name: 'The Economist', re: /economist/i, cat: 'news' },
  { name: 'The Athletic', re: /the\s*athletic/i, cat: 'news' },
  { name: 'Substack', re: /substack/i, cat: 'news' },
  { name: 'Medium', re: /medium\.com|medium corp/i, cat: 'news' },
  { name: 'Readly', re: /readly/i, cat: 'news' },
  { name: 'Patreon', re: /patreon/i, cat: 'other' },
  // Fitness & health
  { name: 'McFit', re: /mcfit|rsg group/i, cat: 'fitness', kind: 'gym' },
  { name: 'FitX', re: /\bfitx\b/i, cat: 'fitness', kind: 'gym' },
  { name: 'clever fit', re: /clever\s*fit/i, cat: 'fitness', kind: 'gym' },
  { name: 'Urban Sports Club', re: /urban\s*sports/i, cat: 'fitness', kind: 'gym' },
  { name: 'EGYM Wellpass', re: /wellpass|egym/i, cat: 'fitness', kind: 'gym' },
  { name: 'Fitness First', re: /fitness\s*first/i, cat: 'fitness', kind: 'gym' },
  { name: 'John Reed', re: /john\s*reed/i, cat: 'fitness', kind: 'gym' },
  { name: 'Freeletics', re: /freeletics/i, cat: 'fitness' },
  { name: 'Strava', re: /strava/i, cat: 'fitness' },
  { name: 'Komoot', re: /komoot/i, cat: 'fitness' },
  { name: 'Headspace', re: /headspace/i, cat: 'fitness' },
  { name: 'Calm', re: /\bcalm\.com|\bcalm\b/i, cat: 'fitness' },
  { name: 'Planet Fitness', re: /planet\s*fitness|pf\s*club/i, cat: 'fitness', kind: 'gym' },
  { name: 'PureGym', re: /pure\s*gym/i, cat: 'fitness', kind: 'gym' },
  { name: 'The Gym Group', re: /the\s*gym\s*(group|ltd)/i, cat: 'fitness', kind: 'gym' },
  { name: 'Anytime Fitness', re: /anytime\s*fitness/i, cat: 'fitness', kind: 'gym' },
  { name: 'LA Fitness', re: /la\s*fitness/i, cat: 'fitness', kind: 'gym' },
  { name: '24 Hour Fitness', re: /24\s*hour\s*fitness/i, cat: 'fitness', kind: 'gym' },
  { name: 'Equinox', re: /equinox/i, cat: 'fitness', kind: 'gym' },
  { name: 'David Lloyd', re: /david\s*lloyd/i, cat: 'fitness', kind: 'gym' },
  { name: 'ClassPass', re: /classpass/i, cat: 'fitness', kind: 'gym' },
  { name: 'Peloton', re: /peloton/i, cat: 'fitness' },
  { name: 'Fitnessstudio', generic: true, re: /fitness|\bgym\b|sportstudio/i, cat: 'fitness', kind: 'gym' },
  // Gaming
  { name: 'PlayStation Plus', re: /playstation|sony interactive/i, cat: 'gaming' },
  { name: 'Nintendo', re: /nintendo/i, cat: 'gaming' },
  { name: 'EA Play', re: /electronic arts|\bea\s*play/i, cat: 'gaming' },
  // Dating
  { name: 'Tinder', re: /tinder/i, cat: 'dating', kind: 'dating' },
  { name: 'Parship', re: /parship/i, cat: 'dating', kind: 'dating' },
  { name: 'ElitePartner', re: /elitepartner/i, cat: 'dating', kind: 'dating' },
  { name: 'Bumble', re: /bumble/i, cat: 'dating', kind: 'dating' },
  { name: 'Hinge', re: /\bhinge\b/i, cat: 'dating', kind: 'dating' },
  { name: 'Match', re: /match\.com|match group/i, cat: 'dating', kind: 'dating' },
  { name: 'LoveScout24', re: /lovescout/i, cat: 'dating', kind: 'dating' },
  // Learning
  { name: 'Duolingo', re: /duolingo/i, cat: 'learning' },
  { name: 'Babbel', re: /babbel/i, cat: 'learning' },
  { name: 'Chegg', re: /chegg/i, cat: 'learning' },
  { name: 'Coursera', re: /coursera/i, cat: 'learning' },
  { name: 'Skillshare', re: /skillshare/i, cat: 'learning' },
  { name: 'MasterClass', re: /masterclass/i, cat: 'learning' },
  { name: 'LinkedIn Premium', re: /linkedin/i, cat: 'learning' },
  // Mobile & internet
  { name: 'Verizon', re: /verizon/i, cat: 'mobile' },
  { name: 'AT&T', re: /\bat\s*&\s*t\b|\batt\*|\batt\s+(bill|payment|mobility)/i, cat: 'mobile' },
  { name: 'T-Mobile', re: /t-?mobile/i, cat: 'mobile' },
  { name: 'Mint Mobile', re: /mint\s*mobile/i, cat: 'mobile' },
  { name: 'Visible', re: /\bvisible\b/i, cat: 'mobile' },
  { name: 'Cricket Wireless', re: /cricket\s*wireless/i, cat: 'mobile' },
  { name: 'Xfinity', re: /xfinity|comcast/i, cat: 'internet' },
  { name: 'Spectrum', re: /spectrum|charter\s*comm/i, cat: 'internet' },
  { name: 'Cox', re: /\bcox\s*comm/i, cat: 'internet' },
  { name: 'BT', re: /\bbt\s*(group|broadband|plc)|bt\.com|british telecom/i, cat: 'internet' },
  { name: 'Virgin Media', re: /virgin\s*media/i, cat: 'internet' },
  { name: 'EE', re: /\bee\s*(ltd|limited)\b/i, cat: 'mobile' },
  { name: 'Three', re: /three\.co\.uk|hutchison\s*3g/i, cat: 'mobile' },
  { name: 'giffgaff', re: /giffgaff/i, cat: 'mobile' },
  { name: 'Telekom', re: /telekom/i, cat: 'mobile' },
  { name: 'Vodafone', re: /vodafone|kabel deutschland|unitymedia/i, cat: 'internet' },
  { name: 'O2 / Telefónica', re: /telefonica|telefónica|\bo2\b/i, cat: 'mobile' },
  { name: '1&1', re: /1\s*&\s*1|1und1|einsundeins/i, cat: 'internet' },
  { name: 'congstar', re: /congstar/i, cat: 'mobile' },
  { name: 'freenet', re: /freenet|mobilcom/i, cat: 'mobile' },
  { name: 'fraenk', re: /fraenk/i, cat: 'mobile' },
  { name: 'PŸUR', re: /pyur|tele columbus/i, cat: 'internet' },
  { name: 'Drillisch / WinSIM', re: /drillisch|winsim|premiumsim/i, cat: 'mobile' },
  // Food boxes
  { name: 'HelloFresh', re: /hellofresh/i, cat: 'food', kind: 'mealkit' },
  { name: 'Marley Spoon', re: /marley\s*spoon/i, cat: 'food', kind: 'mealkit' },
  { name: 'Lieferando Plus', re: /lieferando/i, cat: 'food', kind: 'delivery' },
  { name: 'Wolt+', re: /\bwolt\b/i, cat: 'food', kind: 'delivery' },
  { name: 'Blue Apron', re: /blue\s*apron/i, cat: 'food', kind: 'mealkit' },
  { name: 'Factor', re: /factor\s*75|factor\s*meals/i, cat: 'food', kind: 'mealkit' },
  { name: 'Gousto', re: /gousto/i, cat: 'food', kind: 'mealkit' },
  { name: 'DashPass', re: /dashpass|doordash/i, cat: 'food', kind: 'delivery' },
  { name: 'Uber One', re: /uber\s*one/i, cat: 'food', kind: 'delivery' },
  { name: 'Grubhub+', re: /grubhub/i, cat: 'food', kind: 'delivery' },
  { name: 'Instacart+', re: /instacart/i, cat: 'food', kind: 'delivery' },
  { name: 'Deliveroo Plus', re: /deliveroo/i, cat: 'food', kind: 'delivery' },
  { name: 'Walmart+', re: /walmart\s*\+|walmart\s*plus/i, cat: 'shopping' },
  { name: 'Costco Membership', re: /costco.*member|member.*costco/i, cat: 'other' },
  { name: 'Tesco Clubcard Plus', re: /clubcard\s*plus/i, cat: 'food' },
  // Mobility
  { name: 'Deutschlandticket', re: /deutschland\s*-?\s*ticket|d-ticket|dticket/i, cat: 'mobility' },
  { name: 'ADAC', re: /\badac\b/i, cat: 'mobility' },
  { name: 'Deutsche Bahn', re: /\bdb\s*(fernverkehr|vertrieb)|deutsche bahn|bahncard/i, cat: 'mobility' },
  { name: 'ShareNow / Miles', re: /share\s*now|miles mobility/i, cat: 'mobility' },
  // Broadcasting fee (mandatory, not cancellable)
  { name: 'Rundfunkbeitrag', re: /rundfunk|beitragsservice|ard zdf/i, cat: 'broadcast' },
  { name: 'TV Licence', re: /tv\s*licen[cs]e/i, cat: 'broadcast' },
  // Insurance
  { name: 'Allianz', re: /allianz/i, cat: 'insurance' },
  { name: 'HUK-COBURG', re: /huk/i, cat: 'insurance' },
  { name: 'ERGO', re: /\bergo\b/i, cat: 'insurance' },
  { name: 'AXA', re: /\baxa\b/i, cat: 'insurance' },
  { name: 'DEVK', re: /\bdevk\b/i, cat: 'insurance' },
  { name: 'Generali', re: /generali/i, cat: 'insurance' },
  { name: 'CosmosDirekt', re: /cosmos\s*direkt/i, cat: 'insurance' },
  { name: 'Barmenia', re: /barmenia/i, cat: 'insurance' },
  { name: 'R+V', re: /r\s*\+\s*v\b|ruv versicherung/i, cat: 'insurance' },
  { name: 'GEICO', re: /geico/i, cat: 'insurance' },
  { name: 'State Farm', re: /state\s*farm/i, cat: 'insurance' },
  { name: 'Progressive', re: /progressive\s*(ins|casualty)/i, cat: 'insurance' },
  { name: 'Allstate', re: /allstate/i, cat: 'insurance' },
  { name: 'Versicherung', generic: true, re: /versicherung|insurance/i, cat: 'insurance' },
  // Energy
  { name: 'E.ON', re: /\be\.?on\b/i, cat: 'energy' },
  { name: 'Vattenfall', re: /vattenfall/i, cat: 'energy' },
  { name: 'EnBW', re: /\benbw\b/i, cat: 'energy' },
  { name: 'LichtBlick', re: /lichtblick/i, cat: 'energy' },
  { name: 'Tibber', re: /tibber/i, cat: 'energy' },
  { name: 'Octopus Energy', re: /octopus/i, cat: 'energy' },
  { name: 'Stadtwerke', generic: true, re: /stadtwerke/i, cat: 'energy' },
  { name: 'Con Edison', re: /con\s*ed(ison)?\b/i, cat: 'energy' },
  { name: 'PG&E', re: /pg\s*&\s*e|pacific gas/i, cat: 'energy' },
  { name: 'Duke Energy', re: /duke\s*energy/i, cat: 'energy' },
  { name: 'British Gas', re: /british\s*gas/i, cat: 'energy' },
  { name: 'EDF Energy', re: /\bedf\b/i, cat: 'energy' },
  { name: 'OVO Energy', re: /\bovo\b/i, cat: 'energy' },
  { name: 'Thames Water', re: /thames\s*water/i, cat: 'energy' },
  { name: 'Strom / Gas', generic: true, re: /\bstrom\b|\bgas\b|energie|electric|utilit/i, cat: 'energy' },
  // Housing & finance
  { name: 'Miete', generic: true, re: /\bmiete\b|mietzahlung|hausverwaltung|wohnungsbau|\brent\b|property management|council\s*tax|mortgage/i, cat: 'housing' },
  { name: 'Kredit', generic: true, re: /kredit|darlehen|finanzierung|ratenzahlung|tilgung|\bloan\b|student\s*loan/i, cat: 'finance' },
  { name: 'Kontoführung', generic: true, re: /kontof(ü|ue)hrung|entgelt.*konto|kartenpreis|jahresgeb(ü|ue)hr/i, cat: 'finance' },
  { name: 'Sparplan', generic: true, re: /sparplan|trade republic|scalable|umbuchung|(ü|ue)bertrag|sparen/i, cat: 'finance' },
  // Charity
  { name: 'Spende', generic: true, re: /spende|unicef|greenpeace|wwf|ärzte ohne grenzen|aerzte ohne grenzen|sos-kinderdorf|wikimedia/i, cat: 'charity' },
  // Shopping (broad, last)
  { name: 'Amazon', re: /amazon|amzn/i, cat: 'shopping' },
];

// Payment intermediaries hide the real merchant in the purpose text.
export const INTERMEDIARIES = /paypal|klarna|sofort|stripe|adyen|mollie|sumup|payone|computop|unzer|giropay|wirecard|nexi|worldline|zelle|venmo|cash\s*app/i;

export function findKnownMerchant(text) {
  if (!text) return null;
  // Wallet names show up on ordinary card payments and must not match Google/Apple.
  const cleaned = text.replace(/(google|apple)\s*pay\b/gi, ' ');
  for (const m of MERCHANTS) if (m.re.test(cleaned)) return m;
  return null;
}
